CREATE SEQUENCE SCRIPT_SEQUENCE START WITH 10;
CREATE SEQUENCE REPORT_SEQUENCE START WITH 10;
CREATE SEQUENCE RESULT_SEQUENCE START WITH 10;

DROP TABLE IF EXISTS REPORT;
CREATE TABLE REPORT
(
    ID         BIGINT,
    AUTHOR VARCHAR(255),
    NAME VARCHAR(255),
    DATE_EXECUTE TIMESTAMP,
    primary key (ID)
);

DROP TABLE IF EXISTS RESULT;
CREATE TABLE RESULT
(
    ID          BIGINT,
    SCRIPT_KEY VARCHAR(255),
    NAME VARCHAR(255),
    DOC_NAME VARCHAR(255),
    DATE_CREATED TIMESTAMP,
    DATE_MODIFY TIMESTAMP,
    DATA VARCHAR(255),
    EXAMPLE VARCHAR(255),
    AUTHOR VARCHAR(255),
    RESULT VARCHAR(255),
    primary key (ID)
);

DROP TABLE IF EXISTS SCRIPT;
CREATE TABLE SCRIPT
(
    ID          BIGINT,
    SCRIPT_KEY VARCHAR(255),
    NAME VARCHAR(255),
    DOC_NAME VARCHAR(255),
    DATE_CREATED TIMESTAMP,
    DATE_MODIFY TIMESTAMP,
    DATA VARCHAR(255),
    EXAMPLE VARCHAR(255),
    AUTHOR VARCHAR(255),
    primary key (ID)
);

DROP TABLE IF EXISTS REPORT_RESULT;
CREATE TABLE REPORT_RESULT
(
    REPORT_ID  BIGINT references REPORT (ID) on delete cascade,
    RESULT_ID BIGINT references RESULT (ID),
    primary key (REPORT_ID, RESULT_ID)
);
